repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1024
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.2
    hooks:
      - id: check-github-workflows
      - id: check-renovate
  - repo: local
    hooks:
      - name: Lint GitHub Actions workflows
        id: actionlint
        entry: mise exec -- actionlint
        files: ^\.github/workflows/.*\.ya?ml$
        language: system
      - name: Lint Dockerfiles
        id: hadolint
        entry: mise exec -- hadolint
        files: (^|/)Dockerfile(\.[^/]+)?$
        language: system
        args:
          - --failure-threshold
          - error
      - name: Check formatting
        id: prettier
        entry: mise exec -- prettier --check
        files: \.(css|html|js|json|md|yaml)$
        language: system
      - name: Lint Python
        id: ruff-check
        entry: mise exec -- ruff check --extend-select I
        language: system
        types:
          - python
      - name: Check Python formatting
        id: ruff-format
        entry: mise exec -- ruff format --check
        language: system
        types:
          - python
